[workspace]
resolver = "2"
members = [
    "crates/cross-kit",
    "crates/cross-kit-codegen",
    "crates/cross-kit-core",
    "crates/cross-kit-macros",
    "crates/cross-kit-packager-ios",
    "crates/cross-kit-cli",
    "example/shared",
]
exclude = ["tools/ck-swift-packager"]

[workspace.package]
edition = "2024"
license = "MIT"
