[shared]
crate_path = "shared"
package = "shared"
lib_name = "cross_kit_shared"
metadata_bin = "ck_vm_metadata"

[ios]
package_name = "CrossKitShared"
output = "dist/ios"
targets = ["ios", "ios-sim", "ios-sim-x86_64"]
build_mode = "release"
lib_type = "static"
format = "spm"
swift_bridges = true

[android]
package_name = "com.crosskit.shared"
output = "android/app/build/generated/cross-kit"
jni_libs_output = "android/app/src/main/jniLibs"
package_output = "dist/android"
gradle_project_output = "dist/android/gradle-project"
module_name = "crosskitshared"
gradle_executable = "android/gradlew"
targets = ["arm64-v8a", "x86_64"]
build_mode = "release"
