[bindings.kotlin]
package_name = "com.crosskit.formwizard.shared"
cdylib_name = "cross_kit_form_wizard_shared"

[bindings.swift]
module_name = "CrossKitFormWizardShared"
cdylib_name = "cross_kit_form_wizard_shared"
