// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CommonApiError {
    #[prost(enumeration = "common_api_error::ErrorCode", tag = "1")]
    pub error: i32,
    #[prost(string, tag = "2")]
    pub server_message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `CommonApiError`.
pub mod common_api_error {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum ErrorCode {
        Unknown = 0,
        /// 请求参数非法
        TypeMismatch = 10001,
    }
    impl ErrorCode {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unknown => "Unknown",
                Self::TypeMismatch => "TypeMismatch",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "Unknown" => Some(Self::Unknown),
                "TypeMismatch" => Some(Self::TypeMismatch),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CommonRequest {
    #[prost(string, tag = "1")]
    pub rid: ::prost::alloc::string::String,
    #[prost(oneof = "common_request::Request", tags = "301, 201, 202, 203, 401")]
    pub request: ::core::option::Option<common_request::Request>,
}
/// Nested message and enum types in `CommonRequest`.
pub mod common_request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Request {
        #[prost(message, tag = "301")]
        GetWordInfo(super::GetWordInfoRequest),
        #[prost(message, tag = "201")]
        GetSongById(super::GetSongByIdRequest),
        #[prost(message, tag = "202")]
        GetSongRecommend(super::GetSongRecommendRequest),
        #[prost(message, tag = "203")]
        SearchSong(super::SearchSongRequest),
        #[prost(message, tag = "401")]
        Login(super::LoginRequest),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommonResponse {
    #[prost(string, tag = "2")]
    pub rid: ::prost::alloc::string::String,
    #[prost(oneof = "common_response::Response", tags = "1, 301, 201, 202, 203, 401")]
    pub response: ::core::option::Option<common_response::Response>,
}
/// Nested message and enum types in `CommonResponse`.
pub mod common_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Response {
        #[prost(message, tag = "1")]
        Error(super::CommonApiError),
        #[prost(message, tag = "301")]
        GetWordInfo(super::GetWordInfoResponse),
        #[prost(message, tag = "201")]
        GetSongById(super::GetSongByIdResponse),
        #[prost(message, tag = "202")]
        GetSongRecommend(super::GetSongRecommendResponse),
        #[prost(message, tag = "203")]
        SearchSong(super::SearchSongResponse),
        #[prost(message, tag = "401")]
        Login(super::LoginResponse),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSongByIdRequest {
    #[prost(int32, tag = "1")]
    pub id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSongByIdResponse {
    #[prost(message, optional, tag = "1")]
    pub song: ::core::option::Option<super::song::Song>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSongRecommendRequest {
    #[prost(int32, tag = "1")]
    pub last_recommended_id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSongRecommendResponse {
    #[prost(int32, tag = "2")]
    pub recommended_id: i32,
    #[prost(message, repeated, tag = "3")]
    pub briefs: ::prost::alloc::vec::Vec<super::song::SongBrief>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SearchSongRequest {
    #[prost(string, tag = "1")]
    pub keyword: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchSongResponse {
    #[prost(message, repeated, tag = "1")]
    pub briefs: ::prost::alloc::vec::Vec<super::song::SongBrief>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginRequest {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginResponse {
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<super::user::UserModel>,
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetWordInfoRequest {
    #[prost(string, tag = "1")]
    pub word: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetWordInfoResponse {
    #[prost(message, repeated, tag = "1")]
    pub word_infos: ::prost::alloc::vec::Vec<super::word_info::WordInfo>,
}
/// / 获取用户信息
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUserRequest {
    #[prost(uint32, tag = "1")]
    pub id: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUserResponse {
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<super::user::UserModel>,
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
}
