// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PassportApiError {
    #[prost(enumeration = "passport_api_error::ErrorCode", tag = "1")]
    pub error: i32,
    #[prost(string, tag = "2")]
    pub server_message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `PassportApiError`.
pub mod passport_api_error {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum ErrorCode {
        Unknown = 0,
        /// 请求参数非法
        TypeMismatch = 1,
        /// 登录密码错误
        PasswordNotCorrect = 2,
    }
    impl ErrorCode {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unknown => "Unknown",
                Self::TypeMismatch => "TypeMismatch",
                Self::PasswordNotCorrect => "PasswordNotCorrect",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "Unknown" => Some(Self::Unknown),
                "TypeMismatch" => Some(Self::TypeMismatch),
                "PasswordNotCorrect" => Some(Self::PasswordNotCorrect),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PassportApiRequest {
    #[prost(oneof = "passport_api_request::Payload", tags = "1, 2")]
    pub payload: ::core::option::Option<passport_api_request::Payload>,
}
/// Nested message and enum types in `PassportApiRequest`.
pub mod passport_api_request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "1")]
        V1UserRegister(super::V1PassportRegisterRequest),
        #[prost(message, tag = "2")]
        V1UserLogin(super::V1PassportLoginRequest),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PassportApiResponse {
    #[prost(oneof = "passport_api_response::ResponseBody", tags = "2, 3")]
    pub response_body: ::core::option::Option<passport_api_response::ResponseBody>,
}
/// Nested message and enum types in `PassportApiResponse`.
pub mod passport_api_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum ResponseBody {
        #[prost(message, tag = "2")]
        V1UserRegister(super::V1PassportRegisterResponse),
        #[prost(message, tag = "3")]
        V1UserLogin(super::V1PassportLoginResponse),
    }
}
/// 用户注册
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct V1PassportRegisterRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub phone: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct V1PassportRegisterResponse {
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<super::user::UserModel>,
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
}
/// 用户登录
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct V1PassportLoginRequest {
    #[prost(string, tag = "1")]
    pub account: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct V1PassportLoginResponse {
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<super::user::UserModel>,
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
}
