// This file is @generated by prost-build.
#[derive(sqlx::FromRow)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LyricElement {
    #[prost(string, tag = "1")]
    pub surface: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub is_oov: bool,
    #[prost(string, tag = "3")]
    pub normalized_form: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub reading_form: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub info: ::prost::alloc::string::String,
}
#[derive(sqlx::FromRow)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Lyric {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub zh_translation: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub elements: ::prost::alloc::vec::Vec<LyricElement>,
    #[prost(string, tag = "4")]
    pub start_time: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub end_time: ::prost::alloc::string::String,
}
#[derive(sqlx::FromRow)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Song {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub author: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "4")]
    pub lyrics: ::prost::alloc::vec::Vec<Lyric>,
}
#[derive(sqlx::FromRow)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SongBrief {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub author: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
