// This file is @generated by prost-build.
#[derive(sqlx::FromRow)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WordInfo {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub word: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub pronounce: ::prost::alloc::string::String,
    #[prost(int32, repeated, tag = "4")]
    pub tone: ::prost::alloc::vec::Vec<i32>,
    #[prost(message, repeated, tag = "5")]
    pub cn_meaning: ::prost::alloc::vec::Vec<WordSense>,
    #[prost(string, tag = "6")]
    pub normalized_form: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub form_desc: ::prost::alloc::string::String,
}
#[derive(sqlx::FromRow)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WordSense {
    #[prost(string, tag = "1")]
    pub part: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub meanings: ::prost::alloc::vec::Vec<WordMeaning>,
}
#[derive(sqlx::FromRow)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WordMeaning {
    #[prost(string, tag = "1")]
    pub meaning: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub egs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "3")]
    pub egts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
